### ISSUE TITLE
Type system tracker

### ISSUE THREAD

**Issue by rachitnigam** [cucapra/seashell#8]
Global tracker for the compiler and the type system. 

- [ ] Bounds checking

### Done 
- [x] Multidimensional array accesses
- [x] Index type arithmetic 
- [x] Implement sized ints
- [x] Fix #6
- [x] Read/Write capabilities
- [X] Proper test harness.
- [x] Add comments explaining functions in `type.ml`
- [x] Improve error messages from the parser/lexer
- [X] Use `ocaml-ppx` for the AST.
- [X] Turn `seac` into a proper CLI with some help info.
